use_frameworks!

target 'JCToolKit_Example' do
  pod 'JCToolKit', :path => '../'

  target 'JCToolKit_Tests' do
    inherit! :search_paths
    
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
